### ISSUE TITLE
Clarification on slurm tasks in the workflow

### ISSUE THREAD

**Issue by adavanisanti** [LPM-HMS/COSMOS2#72]
Hi, I am using cfncluster to create clusters on AWS and evaluating cosmos for workflow management. 

As per documentation, tasks are bash scripts. For slurm, should these scripts be the ones that I submit through sbatch? If so, how do I set specific tasks in the workflow to use slurm?

Appreciate any examples.

Thanks
Santi

**Comment by egafni** [comment]
For slurm, yes they get submitted to sbatch.  To use slurm, youd specify
your default_drm as 'slurm' when you start youelr Cosmos session.

 Workflow.add_task also has a drm parameter that allows you to specify a
particular drm for that Task.

On Aug 18, 2017 4:19 PM, "Santi Adavani" <notifications@github.com> wrote:

Hi, I am using cfncluster to create clusters on AWS and evaluating cosmos
for workflow management.

As per documentation, tasks are bash scripts. For slurm, should these
scripts be the ones that I submit through sbatch? If so, how do I set
specific tasks in the workflow to use slurm?

Appreciate any examples.

Thanks
Santi

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LPM-HMS/COSMOS2/issues/72>, or mute the thread

**Comment by egafni** [comment]
Sorry about the typos, typing on a phone!

**Comment by adavanisanti** [comment]
Thanks @egafni. Follow up question: If I have a combination of command line tasks (say wget, unzip etc.) and slurm jobs then what should be the default drm?

**Comment by egafni** [comment]
Depends. Often youll want to bundle the commands into one Task.  Other
times youll want to set drm='local' in add_task

**Comment by adavanisanti** [comment]
That helps. Thanks!
