### ISSUE TITLE
Cosmos examples fail on a fresh install (conda, both python3 and python2.7)

### ISSUE THREAD

**Issue by lucventurini** [LPM-HMS/COSMOS2#83]
Good morning,
                         I am trying to execute the following example from the documentation, which however fails:

```
from cosmos.models.Cosmos import Cosmos

def word_count(in_txt, out_txt, use_lines=False):
    l = ' -l' if use_lines else ''
    return r"""
        wc{l} {in_txt} > {out_txt}
        """.format(**locals())

cosmos = Cosmos('sqlite:///cosmos.sqlite')
cosmos.initdb()
workflow = cosmos.start('My_Workflow', 'out_dir')

wc_tasks = [ workflow.add_task(word_count, params=dict(in_txt=f),
                                                       uid=str(i))
             for i,f in enumerate(('a.txt','b.txt')) ]
```

- 1: the import should be "from cosmos.models.Cosmos import Cosmos", *not* "from cosmos import Cosmos". The latter fails on the latest installation.

- 2: the workflow fails in any case, due to an SQLAlchemy issue (version 1.2.7):

```
sqlalchemy.exc.InvalidRequestError: When initializing mapper Mapper|Workflow|workflow, expression 'Stage.number' failed to locate a name ("name 'Stage' is not defined"). If this is a class name, consider adding this relationship() to the <class 'cosmos.models.Workflow.Workflow'> class after both dependent classes have been defined.
```

**Comment by ptonellato** [comment]
Chao, Yan and you will resolve this - and then please post the corrected test cases w latest and accurate code and comments

PJT

Typos, awkward phrasing, and unruly implications courtesy of an explosively smart device

On May 18, 2018, at 6:29 AM, Luca Venturini <notifications@github.com<mailto:notifications@github.com>> wrote:


Good morning,
I am trying to execute the following example from the documentation, which however fails:

"""
from cosmos.models.Cosmos import Cosmos

def word_count(in_txt, out_txt, use_lines=False):
l = ' -l' if use_lines else ''
return r"""
wc{l} {in_txt} > {out_txt}
""".format(**locals())

cosmos = Cosmos('sqlite:///cosmos.sqlite')
cosmos.initdb()
workflow = cosmos.start('My_Workflow', 'out_dir')

wc_tasks = [ workflow.add_task(word_count, params=dict(in_txt=f),
uid=str(i))
for i,f in enumerate(('a.txt','b.txt')) ]
"""

1: the import should be "from cosmos.models.Cosmos import Cosmos", not "from cosmos import Cosmos". The latter fails on the latest installation.
2: the workflow fails in any case, due to an SQLAlchemy issue (version 1.2.7):

"""
sqlalchemy.exc.InvalidRequestError: When initializing mapper Mapper|Workflow|workflow, expression 'Stage.number' failed to locate a name ("name 'Stage' is not defined"). If this is a class name, consider adding this relationship() to the <class 'cosmos.models.Workflow.Workflow'> class after both dependent classes have been defined."""

**Comment by egafni** [comment]
Thanks! I will update the docs

I have not used conda, can you give me the command to reproduce the environment?

Does running the examples in the examples/ directory work for you?

**Comment by egafni** [comment]
Updated docs are here:
http://cosmos.hms.harvard.edu/COSMOS2/workflows/workflows.html

I tried that code in my environment and it worked, please let me know if you still have issues

**Comment by lucventurini** [comment]
Hi @egafni,
                    there is a bug in the `start` call, out_dir is interpreted by the method as being the "restart" parameter. I would amend the snippet like this:

```
from cosmos.api import Cosmos

def word_count(in_txt, out_txt, use_lines=False):
    l = ' -l' if use_lines else ''
    return r"""
        wc{l} {in_txt} > {out_txt}
        """.format(**locals())

cosmos = Cosmos('sqlite:///:memory:')
cosmos.initdb()
workflow = cosmos.start('My_Workflow', skip_confirm=True)

wc_tasks = [ workflow.add_task(word_count, params=dict(in_txt=inp, out_txt=out),
                                                       uid=str(i))
             for i, (inp, out) in enumerate((('a.txt', 'a_out.txt'), ('b.txt', 'b_out.txt'))) ]

workflow.run()
```

Changes:
- using an in-memory, discarded sqlite database instead of a permanent one.
- removing the "out_dir" parameter, which is wrongly and confusingly interpreted as the "restart" keyword
- using the "skip_confirm" keyword
- the snippet was missing the definition of the output files. The new snippet includes them
- adding the "run" method at the end to run the workflow

Best

**Comment by lucventurini** [comment]
Regarding Conda, I installed it with:
```
conda create -n py365 python==3.6.5
pip install cosmos
```

I would suggest adding cosmos to conda as well, given its rising popularity in the bioinformatics community.

**Comment by egafni** [comment]
Thanks a lot for that!  I've updated the docs

That's exciting if its popularity is growing - it's pretty hard to tell aside from the occasional word of mouth

**Comment by lucventurini** [comment]
Hi @egafni,
                    I am experimenting with Cosmos in these days. I have to say that I like a lot of its features - coming from Snakemake, it's a relief being able to define clearly inputs and outputs of each function. I certainly hope its popularity may grow quickly (unfortunately I was referring to Conda itself in the previous comment).

I would like a couple of clarifications, which might be better explained in the docs. 

- Is there any way to define a configuration dictionary that will be accessible by the functions, to get the parameters? Otherwise said, when I create the workflow, is it possible to define a configuration which will be passed to all the attached functions? 
- Is there a way to define arbitrary submission command line arguments through DRMAA? If so, how?

I am still experimenting, your Cosmos is a really pipeline manager, and I am just trying to understand all the nuances.

**Comment by egafni** [comment]
re: conda Oh haha!

You can just import configuration options and use them in the functions

settings.py
```
config = dict(option=1)
```

tools.py
```
from settings import config
def my_tool():
     return fr"""
    cmd {config[option]}
     """
```

Re: custom submission commands through DRMAA: see the `get_submit_args` parameter of the Cosmos.__init__ function.  there's a default function passed in, but you can pass your own to control the DRM parameters.

Thanks a lot for the help with the docs!

**Comment by egafni** [comment]
quick note:  conda build is in the works, will try to PR into bioconda soonish
